pipeline:
  docker_master:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: metwork/mfext-centos6-buildimage
    tags:
      - latest
      - ${DRONE_BRANCH}
    when:
      branch: master
      event: push
  docker_not_master:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: metwork/mfext-centos6-buildimage
    tags:
      - ${DRONE_BRANCH}
    when:
      event: push
      branch: 
        excludes: master
  slack:
    image: plugins/slack
    channel: dev
    username: drone
    when:
      status: [ failure ]
    secrets: [ slack_webhook ]
  trigger:
    image: plugins/downstream
    fork: true
    repositories:
      - metwork-framework/mfext@${DRONE_BRANCH}
    secrets: [ downstream_token, downstream_server ]
    when:
      status: [ success ]
      event: push
