pipeline:
  docker_master:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: metwork/mfext-centos6-buildimage
    tags:
      - latest
      - ${DRONE_BRANCH}
    when:
      branch: master
      event: push
  docker_not_master:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: metwork/mfext-centos6-buildimage
    tags:
      - ${DRONE_BRANCH}
    when:
      event: push
      branch: 
        excludes: master
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: dev
    username: drone
